name: 'ChatGPT release text'
description: 'Create a release body using ChatGPT'
author: 'Post Op'
inputs:
  version:
    required: true
    description: 'the release name'
  whimsical:
    required: false
    description: 'whether to create a plain release text or a whimsical one'
    default: 'false'
  sha:
    required: false
    description: 'the starting sha or committish for getting commit messages. uses the latest release as base or the whole of main if there are no releases'
  project_name:
    required: false
    description: 'the project name to communicate to ChatGPT, uses the repo name if not set'
runs:
  using: 'node16'
  main: 'dist/index.js'
